### ISSUE TITLE
Contribution: Dynamic list

### ISSUE THREAD

**Issue by werdnanoslen** [carbon-design-system/carbon-contribution#10]
I'd call this a dynamic list. The goal was to allow a user to quickly build a list of items. I'm personally using this pattern in a couple of places to allow a user to type a list of emails and make a binary admin/not-admin selection for each one. This would not have been possible as a csv list in a text area, and the table component is far too heavy visually for such a simple list.

Here's what that looks like in one case (without the admin selection):
![image](https://user-images.githubusercontent.com/764090/53256832-d2bb5f00-3696-11e9-86d9-73714a361f82.png)

Cyrus Furtado (`@cfurtado` on Slack & IBM Github) on my team built it, and I designed it. 

A simple demo I made from Cyrus' work: https://codesandbox.io/s/523355y4l
Sketch file of a few examples: https://ibm.box.com/s/sdjh2luqirg005ghnvocb0ugsbezrnet

**Comment by werdnanoslen** [comment]
@shixiedesign

**Comment by werdnanoslen** [comment]
Here's a v10 version:
![image](https://user-images.githubusercontent.com/764090/56392276-016d3600-61ff-11e9-8f40-e9f5981ab858.png)

**Comment by shixiedesign** [comment]
Hi @werdnanoslen i finally got to take a closer look. I understand the functionality now. A few thoughts: 

1. there's no visual indicator that it's different from simple text inputs. How about adding a button that says `add` at the end of the inputs? 
2. The "x" clear looks a little big. It should be a 16x16 icon, is it? Checkmark looks good to me, but just FYI this is the checkmark in the icon repo (sorry it's not in sketch yet!) you can grab the [checkmark svg here](https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fcheckmark)
3. Feels like checkmark showing the moment user types anything is a little redundant. I'd not bother with adding a checkmark, and just have an add button instead. 

Here's my quick proposal. Welcome feedbacks! @laurenmrice @aagonzales 

![image](https://user-images.githubusercontent.com/15144993/57108717-34ccbc00-6cf9-11e9-896c-a2ce1b560110.png)

**Comment by shixiedesign** [comment]
Another proposal: 
![image](https://user-images.githubusercontent.com/15144993/57108928-c4726a80-6cf9-11e9-9fd0-fbc4e5b5e289.png)

**Comment by werdnanoslen** [comment]
To points 1 & 3: Fair, although my blue checkmark is that add button, just inline with the field. Your second proposal makes sense, too.

To point 2: The X is more of a "delete" button than clear, it removes that item from the list. And in my latest iterations I changed it to the 16 icon

Here's a quick gif of just the interaction design, not including some visual changes I've I made:
![May-03-2019 16-40-06](https://user-images.githubusercontent.com/764090/57164448-23031b80-6dc2-11e9-8a41-5bb541f466b9.gif)

**Comment by laurenmrice** [comment]
I think in this situation that the plus reads better as an actual button. Typically we use that check icon in a form field as a success indicator only, not that it has an action to click on.

**Comment by werdnanoslen** [comment]
agreed, totally down for that

**Comment by shixiedesign** [comment]
Continue to track in `carbon` repo issue for the next step: https://github.com/carbon-design-system/carbon/issues/2679
