### ISSUE TITLE
Text Entry: Read-only

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-contribution#13]
_Name of the component that the contributor wants to change_
**Text Entry**

_Explanation of why the contributor wants the change and thinks it's necessary_
This request is to handle a text entry component that is filled, but is no longer editable. 

My product has a very common use case for text that has been entered by one user and is important data for consumption, but can no longer be edited for a variety of reasons. The “Disabled” option is not viable, as the label and entered data is not accessible. Proposal is to simply remove the line at the base of the "Filled" version of the component, so that it closely matches with the Disabled component, but passes accessibility.
![Text Entry: Read Only](https://user-images.githubusercontent.com/21066152/54460323-9d5adc00-473f-11e9-9210-4eea981999eb.jpg)

Box folder:
https://ibm.box.com/s/m2hv0o3plpadsttr5ss6rze7ids34co1

Contact:
Jordan Smith
jordanwsmith15
smithjor@us.ibm.com

**Comment by JordanWSmith15** [comment]
@joshblack @shixiedesign

**Comment by shixiedesign** [comment]
@JordanWSmith15 This makes sense to me! Thanks for the contribution. We are currently in V10's last push so we might not get to new features this week. I will also take this back to other designers for consensus in case I missed something.

**Comment by shixiedesign** [comment]
@JordanWSmith15 On second thought, loosing the underline makes the field technically a button styling, so it still looks very interact-able. We can consider loosing the background and re-align text...

**Comment by JordanWSmith15** [comment]
@shixiedesign  That also works. That way, it becomes more of a label with data under it. We would need to consider what text overflow looks like. Would it be cut off by an ellipsis or something?

**Comment by JordanWSmith15** [comment]
Two views to consider:
![Screen Shot 2019-03-26 at 12 12 56 PM](https://user-images.githubusercontent.com/21066152/55013962-867a7c00-4fc0-11e9-8940-189f45256106.png)

**Comment by JordanWSmith15** [comment]
@shixiedesign Any update on this? Are we leaning towards option 1 (keeping the line and removing the box)?

**Comment by werdnanoslen** [comment]
I've done the same thing @JordanWSmith15. I made a symbol based on the text input component with the text top-aligned to where the top of the input field used to be:

![image](https://user-images.githubusercontent.com/764090/56982430-51c58b80-6b4f-11e9-8871-04125d635584.png)

![image](https://user-images.githubusercontent.com/764090/56982460-699d0f80-6b4f-11e9-917e-7ef159a081ff.png)

**Comment by shixiedesign** [comment]
Update! @JordanWSmith15 @werdnanoslen 

Spec summary: 

- Read-only variant will be keeping underline and dropping the background of the field. We need the underline for low-vision users to recognize this as a text field. Also loosing the underline makes the element a button-style, which would be confusing. 
- Not moving the text position after all. Keeping text 16px away from left of border helps with preserving the form structure. 
- Cursor hover should be `not-allowed` cursor
- Overflow text in the field will show in tooltip on hover

Below are some in context explorations from @laurenmrice 

![image](https://user-images.githubusercontent.com/15144993/57496411-6fee6280-7298-11e9-82cc-71f2b96e0255.png)
![image](https://user-images.githubusercontent.com/15144993/57496415-75e44380-7298-11e9-8397-3a79fb5e9a75.png)

**Comment by shixiedesign** [comment]
Closing this issue and tracking development of component here: 
https://github.com/carbon-design-system/carbon/issues/2177
Feel free to re-open if you'd like to discuss the design.

**Comment by dianasanborn** [comment]
Hey @shixiedesign !
Just wanted to revisit this quickly — I was curious as to why some of the options explored above were not considered? Specifically the example @werdnanoslen had. I see the value of having a read only option that stays in the same placement as other text inputs when it's in a form with a mix of both read only and editable, but there are also some scenarios where the entire page is read only, and we need a label/value variant that doesn't take up too much space between fields. 

See example below: 
<img width="623" alt="Screen Shot 2019-11-07 at 9 20 13 AM" src="https://user-images.githubusercontent.com/43549567/68397357-12e94180-0141-11ea-9b3a-e9fece42bd32.png">

We also have this showing up in smaller panels, and would love to consider an alternative read only option as well. 

<img width="281" alt="Screen Shot 2019-11-07 at 8 46 23 AM" src="https://user-images.githubusercontent.com/43549567/68397424-2c8a8900-0141-11ea-99b8-c30024c4318d.png">

**Comment by JordanWSmith15** [comment]
@dianatran18 I think for labels with data that are always read-only, a different component is needed, rather than an extension on the inputs. My team created this to handle your usecase: https://pages.github.ibm.com/maximo-app-framework/graphite/react/storybook/?path=/story/components-%E2%9C%93-field--field-label-placement-on-top

**Comment by dianatran18** [comment]
Thanks @JordanWSmith15 ! Is this something each team is doing separately, or should we have a Carbon option as well?
