### ISSUE TITLE
Nag modal

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-contribution#15]
From @nicoleroppel at carbon-design-system/carbon-components#1478:

### Summary

Hi! Diana and I would like to contribute a nag modal design back into the new system. We've used the message banners and block notification design provided in the sketch file as reference. 

This is just providing the design.

### Justification

Watson Customer Engagement currently supports and will need:

- Error nag modals
- Warning nag modals
- Confirmation nag modals

We may use them to:

- Draw attention to immediate, important pieces of information.
- Confirm actions that are not reversible.

Screenshot of the design below:

<img width="468" alt="screen shot 2018-11-26 at 2 56 52 pm" src="https://user-images.githubusercontent.com/43546639/49044947-5b605700-f19d-11e8-8fed-d1f998853c2c.png">

<img width="446" alt="screen shot 2018-11-26 at 2 56 57 pm" src="https://user-images.githubusercontent.com/43546639/49044948-5b605700-f19d-11e8-8df4-521859eb45b2.png">

<img width="402" alt="screen shot 2018-11-26 at 2 57 03 pm" src="https://user-images.githubusercontent.com/43546639/49044949-5b605700-f19d-11e8-9d38-ec7d7daa50bc.png">

Link for the sketch file: https://ibm.box.com/s/f3hahv4sdkk6fdejj5j0wsbmco9hrsta

### Contributing designers

Diana Tran - dianatran18
Cooper Sanborn - coopersanborn
Nicole Roppel - nicoleroppel

Let us know if you have any questions!

Thanks!

**Comment by aagonzales** [comment]
Re-opened in mono-repo. Trying to move issues out of this repo in future.
