### ISSUE TITLE
Contribution: Noneditable User Interface Elements

### ISSUE THREAD

**Issue by kaylarakower** [carbon-design-system/carbon-contribution#17]
**Name:** Noneditable User Interface Elements

**Research:** Users of the Enterprise CMS have a form that authors edit and approvers review. Approvers should not be able to edit the form, but need to review for errors and return to the editor to revised as needed. I was directed by Tom Dayton to Sun Web Application,[ 6.8.1 Noneditable User Interface Elements](https://pages.github.ibm.com/CloudIntegrationDesign/sun-guidelines/06-content.html#6.8.1), which describes this exact use case.

**Images:** https://ibm.box.com/s/172j35uz1f0ulclf4x3l7vl508apenvy

**Sketch file:** https://ibm.box.com/s/wfjtwupcp4fcazuplwuzbn871ebx1qeh

**Contributing team:** DrupalOne

**Contributing designer:** Kayla Rakower, kayla.rakower@ibm.com

**Contributing developer:** Chris Wilson, ccwilson@us.ibm.com

**Comment by designertyler** [comment]
Hi @kaylarakower thanks for submitting!

There's a PR open right now to include a read-only state for the text field. Would these specs work for your needs? https://github.com/carbon-design-system/carbon/issues/3018

**Comment by kaylarakower** [comment]
Hi @designertyler,
This would, but has it been tested with users? Obviously I am not a user, but I don't feel that there enough of a difference between the editable state

**Comment by kaylarakower** [comment]
@designertyler This design was created for a slightly use case as none of the fields would be editable, so there is a different state for the accordion as well which I do not believe is covered in #3018. Added a link to this design to that ticket.

**Comment by shixiedesign** [comment]
This feels like a larger component – should we add an alternative form variant? @designertyler @aagonzales This layout could be useful in some situations (probably more common in digital/editorial). 

If yes, then there has to be different inputs styling. 

This is an enhancement category issue though. We will evaluate in more detail next month. Will transfer issue to main carbon repo. Thanks!

**Comment by shixiedesign** [comment]
Issue moved to [carbon-design-system/carbon #3125](https://github.com/carbon-design-system/carbon/issues/3125) via [**ZenHub**](https://www.zenhub.com/)
