### ISSUE TITLE
vertical progress indicator: design kit contribution

### ISSUE THREAD

**Issue by eraymond25** [carbon-design-system/carbon-contribution#21]
Here are all the *items* and *groups* for the vertical progress indicator for the design kit: [Sketch file](https://ibm.box.com/s/pg3jnbxw1hi1yjvvsyc63730tugfr9o4)

Notes:
- The height of the one on the code page seems a bit too tall, 56px is what I'm using in my product so I made it that height, but let me know if there is a reason for the height
- All the *pieces* are already pulled from the correct theme library
- All layers should be correctly pinned and correct override management checked
- I found an error in the G100 `02 Complete` piece (it's currently using a default color rather than `interactive-04` so once that is updated the item will be correct since it's pulling from that

Let me know if you need anything else for this :)

**Comment by aagonzales** [comment]
Duplicate issue
