### ISSUE TITLE
Short tag

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon-contribution#23]
**Component name:** tag

**Why the change is necessary:** The Carbon X tag is significantly taller (24px) than in Carbon 9 (20px).  It does not fit comfortably into the short or compact data tables or the small search field, which means that those elements are unusable if tags need to be incorporated. We are proposing an 18px high tag to allow for sufficient spacing in both situations.

**Research supporting change:** We have heard from our users that they like data density, and that short tables help them scan information faster. During PUP, most users we talked with preferred the short table for resource list, which is why we implemented it. Many users we talk with seem to be using smaller desktop devices. 

<img width="771" alt="Screen Shot 2019-07-16 at 1 13 25 PM" src="https://user-images.githubusercontent.com/39408106/61318809-84386980-a7cb-11e9-91bd-cf2b4a22e6f9.png">

Link: https://ibm.box.com/s/ni1eyykfn6k9k2h66jbzqpsev82c5snc

**Screenshots of proposed design:**

<img width="662" alt="Screen Shot 2019-12-18 at 11 00 23 AM" src="https://user-images.githubusercontent.com/39408106/71106844-9d33b500-2185-11ea-99dd-9ed9e4f8bfc2.png">

![image](https://user-images.githubusercontent.com/39408106/61318873-a92cdc80-a7cb-11e9-9d64-e87ca574ca2d.png)

Resource list with small tags in table and search/filter field
  
**Contributing designer(s) & developer(s):** 

Designer: Virginia Nicholson
Developer: Trevor Wong, CloudPAL team

**Comment by vsnichols** [comment]
@aagonzales Sorry I let this languish - updated the padding to 8px on both sides. I am going to try to work with Trevor to contribute this back to Carbon for January.

**Comment by aagonzales** [comment]
Looks good to me! ✅

**Comment by laurenmrice** [comment]
Closing, because this has been implemented
