### ISSUE TITLE
Contribution: Tab style 2

### ISSUE THREAD

**Issue by kaylarakower** [carbon-design-system/carbon-contribution#24]
In the ideation phase of a feature, we used the as-is tab style and found that our team could not identify where to take their action because the tabs are exactly the same as the body text. Therefore, I recommend adding a second tab style to Carbon, utilizing the pattern used on the carbon site. 

![Screen Shot 2019-07-17 at 12 23 07 PM](https://user-images.githubusercontent.com/48567372/61392796-adb9c980-a88d-11e9-8833-f3f68c26b39a.png)

**Concept**
![Tabs + background](https://user-images.githubusercontent.com/48567372/61410478-5b3ed400-a8b2-11e9-9dad-ce38eacbf1cd.png)

[Sketch file](https://ibm.box.com/s/i036kl7jejakmdn7uxrdamehk05nxg93)

Team: Core Drupal - Marketing Platforms, Cognitive Applications
UX Designer: Kayla Rakower, kayla.rakower@ibm.com

**Comment by laurenmrice** [comment]
`container` tabs have been added to react as a variation https://react.carbondesignsystem.com/?path=/story/tabs--container

**Comment by laurenmrice** [comment]
Closing because container tab variant has been added
