### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by steve8la** [carbon-design-system/carbon-contribution#27]
Inside this page (https://www.carbondesignsystem.com/guidelines/iconography/usage) 

I found 2 broken links In this Resources Section
Resources
Elements package: Icons
Elements package: Icons-React

Best regards
Stefano

**Comment by steve8la** [comment]
I found two more broken links in this page: 
https://www.carbondesignsystem.com/guidelines/iconography/contribute

 IBM Design Language visual style. --> Link is not working
To submit, open a pull request with your icon in the **carbon-icons** repository. --> Link is not working

**Comment by laurenmrice** [comment]
All of these have been fixed! Going to close 🎉
