### ISSUE TITLE
Number Input (mobile enhancement)

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-contribution#3]
Hello! We are proposing an alternate to the current Number Input component. The step inputs on the current component are below industry standards for mobile tap targets at 20X10px, making them difficult to interact with on a mobile device:
![issue](https://user-images.githubusercontent.com/21066152/48632773-bcaf4b80-e98f-11e8-82a8-23b6b9a034f6.jpg)

Our proposal is to split the step inputs to opposite sides of the control (down on the left, up on the right) in order to increase the tap target to 40px, the standard height of a Carbon input component. This is a fairly common UI convention for this type of control, available in Bootstrap and [may other standard UIs](https://www.google.com/search?biw=1345&bih=697&tbm=isch&sa=1&ei=nu3uW6yCFqzTjwTUmonwDw&q=input+spinner+ui&oq=input+spinner+ui&gs_l=img.3...11341.12025..12160...0.0..0.149.507.4j1......1....1..gws-wiz-img.kDZauzljSj0). 
![number input mobile variant](https://user-images.githubusercontent.com/21066152/48633487-6cd18400-e991-11e8-8c76-016fecc937cf.png)
We opted to use the Carbon chevron that is used in the current Number Input, rather than + / - symbols, as it appears more cohesive with the rest of the Carbon inputs. We are very open to suggestions for improvement. 

Sketch file [available here.](https://ibm.box.com/s/nadq7pamlp5oeo39x7xr0kzxxw3vfznq) 

Thank you for your consideration,
Jordan Smith (JordanWSmith15)
smithjor@us.ibm.com

**Comment by joshblack** [comment]
cc @carbon-design-system/design

**Comment by joshblack** [comment]
bump @carbon-design-system/design

**Comment by shixiedesign** [comment]
Hi @JordanWSmith15 Sorry for the extremely late reply. Thanks @joshblack for the reminder. This is definitely an important consideration! Looks like the sketchfile link doesn't work. We might have to tweak this design a bit to make it work for V10 styling. But either way, this is a good catch and we should remove the tiny carets to avoid confusion. 
Another possible solution could be using mobile platform's native number input drawers? Eg. in iOS:

![image](https://user-images.githubusercontent.com/15144993/52813146-c021a400-305e-11e9-9fbe-e6ab66bdcc8e.png)

**Comment by JordanWSmith15** [comment]
@shixiedesign No worries!  Yes, we should definitely use the native keyboard on mobile! I think the one on the right allows for more flexibility (like decimals, which my product uses a lot for numeric inputs).  Also, we should consider a step range when hitting + or -  (For instance, if you are entering a temperature, a step of 1 unit, but for voltage, 5 units). In some instances, my product even need a fractional step (.10 per +/- tap), but this may be too specific for the general carbon component. 

Here are updates for V10, and a sketch file. 

[Numeric Spinner.sketch.zip](https://github.com/carbon-design-system/carbon-contribution/files/2869866/Numeric.Spinner.sketch.zip)

![screen shot 2019-02-15 at 10 48 11 am](https://user-images.githubusercontent.com/21066152/52867906-008d2a80-3110-11e9-9a0f-f023606dc00f.png)

**Comment by shixiedesign** [comment]
@JordanWSmith15 thanks!! This could work. I made a few small tweak to the spec image, and there's now an issue for this fix. We try to use 8px (or it's multiples) for any measurements including spacing, sizing of icon, etc. Your image is accurate, just labeled wrong. 

I will still run this design by Mike later on so maybe expect a few more tweaks. I think we gotta think about if the error state really needs an icon here. We have the strong red border as a secondary visual indicator already. 
 
![image](https://user-images.githubusercontent.com/15144993/52869067-7393a280-310a-11e9-8dc8-1d0dc6e68cfe.png)

**Comment by JordanWSmith15** [comment]
@shixiedesign Sounds good! Agree about the error state icon may not be necessary. Other inputs in V10 all seem to have it, so the main reason I included it was for consistency.  There can also be error text below that I did not include in my design.

**Comment by shixiedesign** [comment]
@JordanWSmith15 Thank you for your contribution! The new mobile variant is merged 🎉
