### ISSUE TITLE
FileUploader - Drag and drop 

### ISSUE THREAD

**Issue by CynZhang** [carbon-design-system/carbon-contribution#4]
### Description
Our product is transitioning to Carbon and we noticed that the File Uploader component doesn't support drag and drop. It's a common interaction that many users are highly habituated to it and we'd like to keep supporting. The Add File CTA opens the file browser but it forces users to go through their file structure and find the file every time. So having a drag and drop is a welcome option that could be particular useful for users who already have their file located in their file explorer. 

### Proposal
1. outline the drop zone in the component UI
2. dragging triggers file type validation and handling
3. on file drop, file gets added.

<img width="424" alt="screen shot 2018-12-19 at 12 03 07 pm" src="https://user-images.githubusercontent.com/46002772/50235524-19829500-0386-11e9-96eb-8733fa2e00a5.png">

**Contact** 
Designer: Cynthia Zhang (cynthiaz@ca.ibm.com)
Developer: Bryan Boyd (bboyd@us.ibm.com), Gustavo Daud (gustavoh@br.ibm.com)

Thank you

**Comment by laurenmrice** [comment]
Hi Cynthia, In our upcoming v10 release of Carbon we will not be supporting the drag and drop functionality within our File Uploader component. 

However we do have a secondary design for an alternative drag/drop file uploader component, it just has not been built yet. 

<img width="471" alt="screen shot 2018-12-19 at 2 25 27 pm" src="https://user-images.githubusercontent.com/43969356/50246498-2eb5ee80-039b-11e9-9c1a-ee5556b168bc.png">

Above is the design example, the dotted line is not surrounding the entire component but it is a similar iteration. If you would like to build this out to use in the meantime and contribute back to us, that would be great!

**Comment by CynZhang** [comment]
@laurenmrice that's great to know. We will surely reference this and build it out. Thanks for sharing.

**Comment by shixiedesign** [comment]
@CynZhang Hi! Want to follow up on this thread to see if the drag&drop file uploader got build. If you have it, and willing to contribute back, we would like to feature it in our core component set. Let us know! Thank you!

**Comment by shixiedesign** [comment]
Issue has been inactive for over 6 months, so I'm closing it. 
However we do want to add this feature and dev work is being tracked here https://github.com/carbon-design-system/carbon/issues/2288
