### ISSUE TITLE
Contribution: Text toolbar

### ISSUE THREAD

**Issue by m-battelli** [carbon-design-system/carbon-contribution#6]
A new component to type guided tasks easily (runbook automation) while improving the collaboration among teams.
Contributor: Myriam Battelli
All files here: https://ibm.box.com/s/4rv1jw7xwuv8c8rvqbxp9057qzlydkva

Screenshot details:
<img width="1238" alt="screen shot 2019-02-12 at 10 47 18" src="https://user-images.githubusercontent.com/47557215/52626558-bc055300-2eb3-11e9-8e77-758208e915ed.png">

<img width="1238" alt="screen shot 2019-02-12 at 10 47 57" src="https://user-images.githubusercontent.com/47557215/52626577-c32c6100-2eb3-11e9-8110-c2fe64321bda.png">

**Comment by m-battelli** [comment]
@carbon-design-system/design

**Comment by m-battelli** [comment]
@joshblack @shixiedesign

**Comment by shixiedesign** [comment]
Looks like you've made a new issue tracking this work here: https://github.com/carbon-design-system/carbon-contribution/issues/6 I will close this one but feel free to let me know if you'd need it open for another reason.
