### ISSUE TITLE
Contribution: Undo icon

### ISSUE THREAD

**Issue by m-battelli** [carbon-design-system/carbon-contribution#7]
Icon designed for a new component, Text toolbar #6 
It can be used to erase the text you have just typed.
Contributor: Myriam Battelli
All files here: https://ibm.box.com/s/c0z2ow5uiexi8zu3s56uhptdwcuq99yp

Screenshot details:
<img width="1184" alt="screen shot 2019-02-12 at 10 53 26" src="https://user-images.githubusercontent.com/47557215/52626894-75642880-2eb4-11e9-81dd-1254d0b9fa64.png">

<img width="409" alt="screen shot 2019-02-12 at 11 09 57" src="https://user-images.githubusercontent.com/47557215/52628003-e99fcb80-2eb6-11e9-8fd4-c16f1e45a666.png">

**Comment by m-battelli** [comment]
@joshblack @shixiedesign

**Comment by joshblack** [comment]
Hi @m-battelli! 👋 For icon contributions, mind submitting to https://github.com/IBM/carbon-elements ? This is where the icon assets are currently living 😄 

We also may have an icon that could address this called reset: https://carbon-elements.netlify.com/icons/examples/preview/#32%2Freset just wanted to share that!

**Comment by m-battelli** [comment]
@joshblack Thanks for your answer! I try to open issues in the right repo 😅

**Comment by joshblack** [comment]
No problem at all @m-battelli! We often open issues in the wrong place too 😂 it's way too confusing!

**Comment by shixiedesign** [comment]
Icon has been added via https://github.com/IBM/carbon-elements/pull/373 ! Thank you!
