### ISSUE TITLE
Contribution: Redo icon

### ISSUE THREAD

**Issue by m-battelli** [carbon-design-system/carbon-contribution#8]
Icon designed for a new component, Text toolbar #6 
It can be used to re-enter the text you have just deleted.
Contributor: Myriam Battelli
All files here: https://ibm.box.com/s/z6ebqcilwvi40dahzyihmhcpvwing2rl

Screenshot details:
<img width="802" alt="screen shot 2019-02-12 at 10 56 53" src="https://user-images.githubusercontent.com/47557215/52627092-f0c5da00-2eb4-11e9-9ecf-e200b6d54179.png">

<img width="409" alt="screen shot 2019-02-12 at 11 09 57" src="https://user-images.githubusercontent.com/47557215/52628405-e22cf200-2eb7-11e9-9799-790dc0ceb3a3.png">

**Comment by m-battelli** [comment]
@joshblack @shixiedesign

**Comment by joshblack** [comment]
Hi @m-battelli! 👋 For icon contributions, mind submitting to https://github.com/IBM/carbon-elements ? This is where the icon assets are currently living 😄

**Comment by shixiedesign** [comment]
Looks like the icon is added by Chris and merged! https://github.com/IBM/carbon-elements/pull/373  🎉 Closing this issue if there's no other to-dos. Thank you @m-battelli !
