### ISSUE TITLE
Contribution: Selected item icon 

### ISSUE THREAD

**Issue by m-battelli** [carbon-design-system/carbon-contribution#9]
Icon designed for a new component, Text toolbar #6 
It can be used for the selection in the list (examples: font style, font color, and font size).
The use of the checkbox or checkmark does not seem correct for these lists.

Contributor: Myriam Battelli
All files here: https://ibm.box.com/s/ze88hjcwaoil5pi26d0llf2zmpy9jf5r

Screenshot details:
<img width="1238" alt="screen shot 2019-02-12 at 10 47 57" src="https://user-images.githubusercontent.com/47557215/52628591-48b21000-2eb8-11e9-97ea-e68d73bb497d.png">

<img width="1429" alt="screen shot 2019-02-12 at 11 20 28" src="https://user-images.githubusercontent.com/47557215/52628604-510a4b00-2eb8-11e9-9075-4fece12d1b6e.png">

**Comment by m-battelli** [comment]
@joshblack @shixiedesign

**Comment by shixiedesign** [comment]
Hi! @m-battelli sorry took me so long to get back to you. We do have a checkmark in the current icon library. Would that serve your need here? This checkmark doesn't have a container. I agree the checkbox or checkmark in circle would not work in this situation. https://carbon-elements.netlify.com/icons/examples/preview/#32%2Fcheckmark

![image](https://user-images.githubusercontent.com/15144993/53918774-7f012c00-402d-11e9-8141-7d08f84c60fd.png)

**Comment by m-battelli** [comment]
Ok, thanks @shixiedesign

**Comment by aagonzales** [comment]
Closing as resolved.
